### ISSUE TITLE
Error: "Failed to set token"

### ISSUE THREAD

**Issue by JFeuchter** [MartinAmps/Shopify-Private-APIs#10]
Hello Im getting an error while trying to use the POST method, each time it returns "Failed to set token" Ive tried many ways of solving this with the ideas posted before, but with no luck. I can actually use the get but I cant use the post, apparently the token is not being made. Any ideas why? Here si part of the code:

`try { $api_shopify->setToken('https://myshop.myshopify.com/admin/discounts/new'); } 
                catch (\Exception $ex) { echo "Error: " . $ex}
$responseOrderShopify = $api_shopify->doRequest('POST', 'orders.json', $MLOrder);`

I tried with the url https://myshop.myshopify.com/admin/draft_orders/new

And I get this error:

`Error: exception 'Exception' with message 'Failed to set token' in /home/mysite/public_html/mysite.com/app/Plugin/Shopify/Controller/InstallController.php:1026`

Also on the print for `$responseOrderShopify` I get the webadmin login. Im not sure if Im doing anything wrong here? Could someone help me ? :D

**Comment by bdunlap** [comment]
looks like Shopify has added some browser-detection logic and scrapers now need to fetch a 'bypass unsupported browser' URL after login. I've written a patch for this library and will submit a pull request shortly.

**Comment by JFeuchter** [comment]
Nice this would be awesome haha I had to do a private app and make a curl calls besides to post what I needed to do. Thanks Ill await for the update and pass that to may code so I dont have a bunch of mixed up code hehe.

**Comment by bdunlap** [comment]
Here's my fix: https://github.com/MartinAmps/Shopify-Private-APIs/pull/11

**Comment by JFeuchter** [comment]
Thanks ! :D

**Comment by MartinAmps** [comment]
Thanks @JFeuchter, @bdunlap I just wrote a couple of comments on your PR. Appreciate the input!

**Comment by myjanky** [comment]
https://github.com/MartinAmps/Shopify-Private-APIs/issues/8#issuecomment-204555702

just to help until the branch gets updated.

**Comment by MartinAmps** [comment]
Thanks folks, merged!
