### ISSUE TITLE
Question: Still working?

### ISSUE THREAD

**Issue by dcworldwide** [MartinAmps/Shopify-Private-APIs#12]
I'm glad someone has done the hard work to research this technique. I was wondering if someone would be so kind to let me know if it still works? Thanks

**Comment by dcworldwide** [comment]
I've observed requests to auth/admin using chrome. Request headers sent from chrome to server are listed below.

Appear shopify is using google catcha, does this mean that this lib no longer works?


```
authenticity_token:Nv56TdgYlKNVV53ekwH4MygOgwqmdfasfadfasdfasLBrNERF60SmZrWMeHEZk76cssOWv3uM/XN5kNJ201WostqHc2Fw==
redirect:
login:myemail
password:dfasdf
g-recaptcha-response:03AIezHSavH4kSWsTs1eiQe1oPWhOYyBauX6ZIo5e9Gcu3vEAsgsWyIxjSztKPOqbQqYPOXaBRW2lyA4pbXaFLV_WXHm_znUNNpPI2U_Y28gtE-J3wLK48yF6DnrNW9P0YTW3b7B2NOKRlrzIBDgQmbpExPKgdwfjxWrHCzKRzZlZb1rU_VNl6rNDZc7MHJqsLiobttKey0a20QpEqjKYgC-LejGU0TcDBh9d324-49tvwNATIz-BTr67HqGPE1DUFnY5ErCNxshAdu3SZeaUOUeKf2l3_Ps_D3unNUsxqCeQNyM_ZgXKGorntXgcSqL65FmcNq2vgEy8v
commit:Log in
```

**Comment by JFeuchter** [comment]
Im using this component for my API and its still working. It still has its flaws every now and then so I would test it. Use the component from bdunlap, you can find it [here](https://github.com/bdunlap/Shopify-Private-APIs/blob/ed005460920346c319901faee92c0eb0a5aae189/shopify.php). All thought I would suggest looking for another component like [THIS](https://github.com/phpclassic/php-shopify) one. 

Good Luck :D

**Comment by MartinAmps** [comment]
Still works to the best of my knowledge- I no longer work for the company I made it for, though. I merged Ben's fix-- the phpclassic one looks much more actively maintained, this is probably best for learning purposes now -- blog post is here: https://ma.rtin.so/reverse-engineering-shopify-private-apis!
