### ISSUE TITLE
When I upload to a server I the token cant be set

### ISSUE THREAD

**Issue by JFeuchter** [MartinAmps/Shopify-Private-APIs#2]
Im getting a really weird error. I've been programming this in localhost so far and it worked out fine, but when I upload it to the server I couldn't use it anymore. The error came out that "Failed to set token." Does this have something to do with the server permissions or am I doing something wrong?  Has anyone stumbled upon this error?

**Comment by klategan** [comment]
Getting the same error. Shopify appears to have changed their login to include an "authenticity_token" hidden field. My guess is that this is loaded by javascript and validated during the auth POST.

**Comment by JFeuchter** [comment]
The login in the API does have a token it creates from the login, but for some reason it does not accept this. The "work around" I used to solve this was I entered my personal username and password from my Shopify store. Right after that I entered the secret key and secret password to have access to the private API and it worked. After that I can use any call to get post or put I want.

**Comment by MartinAmps** [comment]
This is working in the latest push, can you retry?

**Comment by MartinAmps** [comment]
I didn't notice the issue opened here, we hit the issue today for the first time.

**Comment by JFeuchter** [comment]
hehe I dont understand the change you did and why now it works, but it does. Hehehe The only change I saw was the change of the preg_match right? You flipped the meta properties? How did this work? hehehe Awsome men thanks for the change

**Comment by MartinAmps** [comment]
Correct - they reordered them in the markup, it may make sense to make it agnostic of order -- if it happens again that's what I'll do :)

No problem!
