### ISSUE TITLE
'Exception' with message 'Failed to set token '

### ISSUE THREAD

**Issue by myjanky** [MartinAmps/Shopify-Private-APIs#4]
{
EDIT:

Issue resolved after syncing repo. 
this line changed.
meta name="csrf-token" content="(.*)" \/

}
The CSRF token is unable to be set any longer using this application.

this may have to do with filter_var in the set token function. (I have not fully debugged.)

Also, Shopify Plus accounts now have the ability to use the Discounts API. 

Shopify may have also closed the door on this "feature" as it is not offered to accounts that are not Plus accounts.

**Comment by JFeuchter** [comment]
Hehe This error must be going around, I got this error as well. Las time I had this error Martin changed the order of the meta data on line 141. Its really weird cause Im testing this on a localhost and its working, but on my host server its not working anymore D:

**Comment by MartinAmps** [comment]
@myjanky glad it worked after pulling! Maybe I can do better about communicating the updates to those who use this helper.

@JFeuchter are you running the latest version on the server?

**Comment by JFeuchter** [comment]
Yeah Its really weird cause I uploaded it last week and it worked on the server as well. D:

**Comment by myjanky** [comment]
Thanks @MartinAmps. That would help. I should mention that upgrading to Shopify Plus is the way to go if you can justify the $1200/month cost. (we do as our shopify transaction fees were going over $1500/month and Plus waives transactions fees) This enables a couple of cool API features such as the Discounts API. But the Private API is very cool and I still need it for the reports and it drives my Coupon creator. 
If needed I can contribute my example to help get others started. 

@JFeuchter have you tried pushing to your remote. Can you post your diff?

**Comment by JFeuchter** [comment]
Im passing the code through FTP. The version on my LocalHost is working, but the version on my Host is not working. It throws me this error: "Error Exception: exception 'Exception' with message 'Failed to set token'"

**Comment by MartinAmps** [comment]
@myjanky  we do use Shopify Plus, but this API didn't exist in Plus when I wrote it - I maintain it just for anyone who can't justify the costs of Plus right now.

@JFeuchter  That sounds very much like you have the old version on your server. Is it possible you're running some opcode cache that isn't currently invalidating the cache? If you're on IRC (Freenode/Quakenet/EFNet) I'd be happy to walk through debugging it with you.

**Comment by JFeuchter** [comment]
Where could I connect to that IRC Channel? Cause I entered on a Online IRC but see one one D:

**Comment by myjanky** [comment]
all I can say is to make sure your FTP client is overwriting the file with the updated one. 
@MartinAmps you can close this issue as I suspect it is the same one that @JFeuchter is having.

**Comment by JFeuchter** [comment]
@MartinAmps Actualy its really wierd cause if I start the session with my own user and password from my Shopify Store before setting up the secret password and secret user from the private API , the access token works. But if its some time since Ive logged in the toke does not work for some reason

**Comment by MartinAmps** [comment]
Join here: https://webchat.freenode.net/ with channel #shopifyprivateapi

I'll close this out to avoid irritating @myjanky with more notifications ;)
