### ISSUE TITLE
discount creation does not work anymore

### ISSUE THREAD

**Issue by Hrairoo666** [MartinAmps/Shopify-Private-APIs#5]
Just wanted to put it out there. The creation of the discount does not work anymore. I managed to get the get function to work by changing the way the CSRF token get's parsed, but that's about it.

**Comment by MartinAmps** [comment]
@Hrairoo666 sorry I missed this. I believe another issue popped up as a result, reverting this commit: https://github.com/MartinAmps/Shopify-Private-APIs/commit/7d7de047b6691c03d99249d7492f170635ac6431 likely was/is the solution. Thanks for reporting, I'll fix it tomorrow!
