### ISSUE TITLE
Get the Shopify Admin Login Screen

### ISSUE THREAD

**Issue by deztech** [MartinAmps/Shopify-Private-APIs#7]
Using the code below I'm getting the login screen, but the strange thing is that it DID work once and I saw the discount within Shopify.  I'm logged in, but every time I hit my example.php script I get the login screen now.  Any ideas?
-Aaron

```php
<?php

require 'shopify.php';

$api = new \Shopify\PrivateAPI('admin@domain.com', 'AdminPassword', 'https://mystore.myshopify.com/admin');

if (!$api->isLoggedIn() && !$api->login()) {
    echo '<p>invalid credentials</p>';
} else {
    # Create a 5% discount coupon
    $new_discount = ['discount' => [
        'applies_to_id' => '',
        'code' => 'automatic_coupon',
        'discount_type' => 'percentage',
        'value' => 5,
        'usage_limit' => 1,
        'starts_at' => date('Y-m-d\TH:i:sO', mktime(0, 0, 0)),
        'ends_at' => null,
        'applies_once' => false
    ]];

    # Set the CSRF token for the POST request
    try { $api->setToken('https://mystore.myshopify.com/admin/discounts/new'); } 
    catch (\Exception $ex) { }

    $do_discount = $api->doRequest('POST', 'discounts.json', $new_discount);

    print_r($do_discount);
}
```

![image](https://cloud.githubusercontent.com/assets/4874827/12468740/25e090f4-bf9b-11e5-922a-83605e9789e0.png)

**Comment by MartinAmps** [comment]
Hi Aaron! Sorry to hear that. Can you test reverting this commit to see if it solves the problem for you?

https://github.com/MartinAmps/Shopify-Private-APIs/commit/7d7de047b6691c03d99249d7492f170635ac6431

Thanks!

**Comment by deztech** [comment]
Hi Martin, thanks for your quick reply, here's what I found.  Reverting didn't help and I traced it to not being able to write the cookie to the "tmp" directory.  Perhaps that varies host to host.  You may want to have the constructor accept an optional parameter to specify a cookie directory location if the user supplies one.  Works great otherwise, thanks so much!

**Comment by MartinAmps** [comment]
Glad to hear it's working now! Feel free to submit a PR and I'll review, maybe a method to set the directory is better than another constructor arg, though!
