### ISSUE TITLE
user agent string issues

### ISSUE THREAD

**Issue by myjanky** [MartinAmps/Shopify-Private-APIs#8]
I am getting an error page when trying to login. Shopify will not allow me to login using this app it seems.
I am debugging.

 You’re using version 49.0.2623.111 of Chrome, which is <a href="https://docs.shopify.com/manual/intro-to-shopify/logging-in/supported-browsers">not supported by Shopify</a>. You can update to the latest version by selecting "Update Google Chrome" from your browser’s toolbar and restarting Chrome. If you <a href="/admin/unsupported_browser_bypass">continue using the current version</a> some features may not work correctly.

**Comment by myjanky** [comment]
solved kind of

 # Set the CSRF token for the POST request
    try { $api->setToken($store.'/unsupported_browser_bypass'); } 
    catch (\Exception $ex) { 
	echo $ex;
	}

**Comment by MartinAmps** [comment]
Hi, sorry for the late reply here. There's an open PR to address this issue which should get merged shortly. Thanks for the tip @myjanky!
